imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

    # Sonata Core Bundles
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_core.yml }

    # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_user.yml }

    # FOS Feature Bundles
    - { resource: fos/fos_user.yml }

    # Services
    #- { resource: @AppBundle/Resources/config/admin.yml }


framework:
    #esi:             ~
    translator:      { fallback: fr }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        form:
            resources:
                - 'FrameworkBundle:FormTable'
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ccmbenchmark.sharedance_handler
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

mopa_bootstrap:
    form:
        templating: false # default is true

# Assetic Configuration
assetic:
    use_controller: true

# Doctrine Configuration
doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

swiftmailer:
    delivery_address: admin@r-target.com

monolog:
    handlers:
        main:
            ident: md5.r-target.com

parameters:
    public_user.file_directory : /var/nas/md5.r-target.com/upload

#        app:
#            facility: local3
#            type:   syslog
#            level:  debug
#            handler: syslog
#            ident: md5.ccmbdm.com
#            formatter: log.iso_formatter
#            channels: ["app"]

old_sound_rabbit_mq:
    connections:
        default:
            host:     md5.local.ccmbdm.com
            port:     5672
            user:     test
            password: test
            vhost:    /
            lazy:     false
    producers:
            add_match_exchange:
                connection: default
                exchange_options: { name: 'match-exchange', type: direct }
    consumers:
            get_match_exchange:
                connection:       default
                exchange_options: { name: 'match-exchange', type: direct }
                queue_options:    { name: 'match-exchange' }
                callback:         match_exchange_service
