imports:
    - { resource: config.yml }
    - { resource: /etc/quidea/qlf/sharedance_bg.yml }
    - { resource: /etc/quidea/qlf/syslog.yml }
    - { resource: /etc/quidea/qlf/mailing.yml }
    - { resource: /etc/quidea/qlf/db_md5.yml }
    - { resource: /etc/quidea/qlf/rabbitmq.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        console:
            type:  console