home:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true

cga_show:
    path: /cga/
    defaults:  { _controller: AppBundle:Cga:show }

# Matching
match_list:
    path: /matching/
    defaults:  { _controller: ApplicationSonataUserBundle:Matching:show }

match_populate:
    path: /matching/{base}/{campaign}
    defaults:  { _controller: ApplicationSonataUserBundle:Matching:populate }

# Base
base_list:
    path: /bases/
    defaults:  { _controller: ApplicationSonataUserBundle:Base:show }

base_update:
    path: /bases/update/{id}
    defaults:  { _controller: ApplicationSonataUserBundle:Base:update }

base_remove:
    path: /bases/remove/{id}
    defaults:  { _controller: ApplicationSonataUserBundle:Base:remove }

base_details:
    path: /bases/details/{id}
    defaults:  { _controller: ApplicationSonataUserBundle:Base:details }

base_upload:
    path: /bases/upload/
    defaults:  { _controller: ApplicationSonataUserBundle:Base:upload }

# Admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

# Hors admin
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile