<?php

namespace Application\Sonata\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Sonata\UserBundle\Entity\User;

/**
 * BaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends EntityRepository
{
    public function findBasesByUserId(User $user)
    {
        return $this->createQueryBuilder('b')
        ->where('b.user = :user')
        ->setParameter('user', $user)
        ->addOrderBy('b.modificated_at', "DESC");
    }
}
