<?php

namespace Application\Sonata\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Sonata\UserBundle\Entity\User;

/**
 * BaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends EntityRepository
{
    public function findBasesByUserId(User $user)
    {
        return $this->createQueryBuilder('b')
        ->where('b.user = :user')
        ->setParameter('user', $user)
        ->addOrderBy('b.updated_at', "DESC");
    }

    public function findConsumerBases(){
        $null = null;
        $qb = $this->createQueryBuilder('b');

        $t = $qb->select('b.id')
            ->leftJoin('b.campaign', 'bc')
            ->leftJoin('b.user', 'u')
            ->leftJoin('u.groups', 'g')
            ->where('bc IS NULL')
            ->andWhere('g.name IS NULL');
        
        $query = $t->getQuery();

        return $query->execute();
    }

    public function countConsumerBases(User $user){
        $null = null;
        $qb = $this->createQueryBuilder('b');

        $t = $qb->select('COUNT(b)')
            ->where('b.user = :user')
            ->setParameter('user', $user);

        $query = $t->getQuery();

        return $query->getSingleScalarResult();
    }

    public function findAdminBases(){

        $qb = $this->createQueryBuilder('b');

        $t = $qb->select('b')
            ->leftJoin('b.user', 'u')
            ->leftJoin('u.groups', 'g')
            ->where('g.name = :group')
            ->setParameter('group', 'ADMIN')
            ->orderBy('b.updated_at','DESC');

        $query = $t->getQuery();

        return $query;
    }
}
