<?php

namespace Application\Sonata\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Sonata\UserBundle\Entity\BaseDetail;
use Application\Sonata\UserBundle\Entity\User;

/**
 * BaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseDetailRepository extends EntityRepository
{
    public function countBaseDetailByUser(User $user){

        $null = null;
        $qb = $this->createQueryBuilder('bd');

        $t = $qb->select('COUNT(bd)')
            ->leftJoin('bd.base', 'b')
            ->where('b.user = :user')
            ->setParameter('user', $user);

        $query = $t->getQuery();

        return $query->getSingleScalarResult(); // instanceof Doctrine\ODM\MongoDB\EagerCursor
    }
}
