<?php

namespace Application\Sonata\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    public function getCategoryOptions($studyId)
    {
        $ret = array();

        $categories = $this->getEntityManager()
            ->getRepository("Sonata\UserBundle\Entity\BaseGroup")
            ->getQuery()
            ->getResult();

        foreach ($categories as $cat) {
            if (!$cat->getParentCategory()) {
                continue;
            }

            if (!array_key_exists($cat->getParentCategory()->getName(), $ret)) {
                $ret[ $cat->getParentCategory()->getName() ] = array();
            }

            $ret[ $cat->getParentCategory()->getName() ][ $cat->getId() ] = $cat;
        }

        return $ret;
    }
}
